import type { AuditRubric } from "./rubricTypes";

/**
 * REHAB EVALUATOR AUDIT RUBRIC (v2 — full episode)
 * ==================================================
 * Source of truth: "8.2026 Dallas Evaluator Audit.xlsx" -> tab "key" (33
 * criteria, 7 sections, 100 points). Human validation reference: tab
 * "Evaluator Audit 2" (patient James Askew, PT only — see
 * PRE_BUILD_RUBRIC_ANALYSIS.md Ambiguity E.1: no OT human baseline exists).
 *
 * This file REPLACES `evaluationAuditRubric.ts` (renamed, not rebuilt — the
 * 11 Evaluation-scope criteria below are unchanged in substance from that
 * file; see PRE_BUILD_RUBRIC_ANALYSIS.md Section G item 1). It ADDS the 22
 * criteria for Progress Notes, Daily Notes, Recertification, and Discharge
 * Summary that were out of scope for v1.
 *
 * Every rubric decision below was explicitly confirmed with the audit
 * program owner in PRE_BUILD_RUBRIC_ANALYSIS.md before being encoded here —
 * see that file's "Confirmed Rubric Decisions Log" for the full reasoning.
 * DC_COMPLETED_TIMELY is the one criterion still marked NEEDS_CONFIRMATION:
 * per that decision, the app reports the factual calendar-day gap and
 * status PENDING_RUBRIC_CONFIRMATION rather than inventing a tier scale.
 */
export const evaluatorAuditRubric: AuditRubric = {
  id: "evaluatorAuditRubric",
  module: "REHAB_EVALUATOR_AUDIT",
  version: "2.0.0",
  sourceOfTruth: "8.2026 Dallas Evaluator Audit.xlsx :: key tab (33 criteria / 100 points)",
  criteria: [
    // ==================================================================
    // SECTION: Evaluation Medical Review (9 pts)
    // ==================================================================
    {
      id: "EVAL_MEDICAL_HISTORY",
      section: "Evaluation Medical Review",
      title: "Contains Medical History",
      keyComment: '"See chart" is not acceptable and automatic 0.',
      maxPoints: 3,
      scoringType: "automatic-zero-phrase-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      automaticZero: {
        phrases: ["see chart", "refer to chart", "per chart", "see medical record", "see h&p", "see hospital records"],
        reason: "Documentation defers to a chart reference instead of stating history — automatic 0, no partial credit.",
      },
      // Content anywhere in the SAME evaluation document satisfies this
      // criterion, not only a dedicated "Medical History" field (confirmed
      // 9/1/2026) — a bare diagnosis code with no narrative still fails.
      evidenceTargets: ["medicalHistory", "reasonForReferral", "priorHospitalizations", "comorbidities"],
      fullCreditDescription:
        "Patient-specific medical history (diagnoses, comorbidities, hospitalization, surgical history, falls/injuries, or a relevant systemic condition) is documented in prose anywhere in the evaluation — not merely a bare diagnosis code.",
    },
    {
      id: "EVAL_MEDICATIONS",
      section: "Evaluation Medical Review",
      title: "Contains Medications List",
      keyComment: '"See MAR" is not acceptable and automatic 0.',
      maxPoints: 3,
      scoringType: "automatic-zero-phrase-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      automaticZero: {
        phrases: ["see mar", "refer to mar", "per facility mar", "see medication list", "see chart", "refer to chart"],
        reason: "Documentation defers to the MAR/chart instead of naming a medication — automatic 0, no partial credit.",
      },
      evidenceTargets: ["medications"],
      fullCreditDescription:
        "At least one specific, clinically relevant medication (or a medication class where the actual medication is otherwise clearly identifiable) is documented anywhere in the evaluation. A complete MAR reproduction is not required, and additional un-named medications never reduce the score.",
    },
    {
      id: "EVAL_COMPLETED_TIMELY",
      section: "Evaluation Medical Review",
      title: "Completed Timely",
      keyComment: "Same day = 3, next day = 2, 2 days = 1, >48 hrs = 0.",
      maxPoints: 3,
      scoringType: "timeliness-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      timingRules: [
        { calendarDays: 0, points: 3 },
        { calendarDays: 1, points: 2 },
        { calendarDays: 2, points: 1 },
        { calendarDaysMin: 3, points: 0 },
      ],
      dateSource: "evaluating_therapist_completion_signature",
      prohibitedDateSources: [
        "physician_signature", "physician_certification", "physician_order",
        "progress_note_signature", "discharge_signature", "batch_report_date",
        "pdf_creation_date", "certification_period_end_date",
      ],
      evidenceTargets: ["evaluationDOS", "therapistSignatureDate"],
      fullCreditDescription: "Evaluating therapist's completion/signature date is the same calendar date as the evaluation date of service. Calendar-day difference, not elapsed hours; a later cosignature never changes this score.",
    },

    // ==================================================================
    // SECTION: Evaluation (19 pts)
    // ==================================================================
    {
      id: "EVAL_HEALTH_STATUS_REFERRAL",
      section: "Evaluation",
      title: "Health Status / Reason for Referral",
      keyComment: "Reason for referral needs to show change; falls reported must be in PCC and must coincide with diagnosis used.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      pcc: {
        dependent: true,
        entireCriterion: false,
        reasonTemplate: "A fall or fall-related event is documented as part of the referral/health status narrative, which the Key requires be corroborated in PCC and checked for coincidence with the diagnosis used.",
        recommendedAction: "Verify the reported fall against the corresponding PCC nursing note or incident report, and confirm the diagnosis used coincides with that fall.",
      },
      evidenceTargets: ["reasonForReferral", "medicalDiagnosis", "treatmentDiagnosis", "fallHistory", "plofFunctionalItems", "clofFunctionalItems"],
      fullCreditDescription:
        "A clear, patient-specific reason for referral is documented, a meaningful health-status/functional change is documented, and it is clinically consistent with the diagnosis used — evaluated as a clinical relationship, not exact wording. A fall triggers a SEPARATE PCC Fall Validation output (Fall Documented in PCC / Fall Coincides With Diagnosis Used) that never reduces this score merely because PCC evidence wasn't uploaded.",
    },
    {
      id: "EVAL_OBJECTIVE_TEST",
      section: "Evaluation",
      title: "Objective Tests / Standardized Test",
      keyComment: "Appropriate test = 3, everything else = 0.",
      maxPoints: 3,
      scoringType: "binary-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      approvedTestsByDiscipline: {
        PT: ["TUG", "Berg Balance Scale", "Tinetti/POMA", "5x Sit-to-Stand", "30-Second Chair Stand", "6-Minute Walk Test", "10-Meter Walk Test", "Functional Reach", "Gait Speed", "Sitting Balance Scale", "Elderly Mobility Scale"],
        OT: ["Barthel Index", "Self-Care Function Score", "Mobility Function Score"],
        SLP: [],
      },
      ambiguityNote: "The spec's own illustrative PT list omitted Sitting Balance Scale and Elderly Mobility Scale, both accepted 3/3 by the human validation example — seeded here from the spec's examples plus every measure confirmed accepted. List is extensible via config only.",
      evidenceTargets: ["objectiveTests"],
      fullCreditDescription: "A recognized, discipline-appropriate standardized/objective measure was actually administered with a scored result (not NT / Not Tested / Not Attempted).",
    },
    {
      id: "EVAL_THERAPIST_ASSESSMENT",
      section: "Evaluation",
      title: "Therapist Assessment",
      keyComment: "PLOF-to-CLOF change noted; pain correlates with goals/diagnosis; documented by nursing in PCC.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      pcc: {
        dependent: true,
        entireCriterion: false,
        reasonTemplate: "The Key expects the therapist's assessment to be cross-referenced against nursing documentation in PCC, which is not present in the uploaded record.",
        recommendedAction: "Cross-reference the therapist's functional assessment against nursing documentation in PCC.",
      },
      evidenceTargets: ["plofFunctionalItems", "clofFunctionalItems", "painStatement"],
      fullCreditDescription: "A clear PLOF-to-CLOF functional change is documented, and if pain is present, it is connected to the goals/diagnosis. Nursing PCC cross-reference is flagged separately as external validation, not scored here.",
    },
    {
      id: "EVAL_ORDERS_IN_PCC",
      section: "Evaluation",
      title: "Orders in PCC",
      keyComment: "Yes = 3, no = 0.",
      maxPoints: 3,
      scoringType: "binary-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      pcc: {
        dependent: true,
        entireCriterion: true,
        reasonTemplate: "The uploaded therapy documentation does not contain PCC order evidence (a physician's Plan of Treatment certification within the eval document is not, by itself, proof of a PCC order).",
        recommendedAction: "Verify discipline, therapy order, frequency, duration, and effective date directly in PCC.",
        acceptableProxyEvidence: false,
      },
      evidenceTargets: ["frequency", "duration", "certificationStart", "certificationEnd"],
      fullCreditDescription: "A matching therapy order (discipline, frequency, duration, effective date) is confirmed present in PCC.",
    },
    {
      id: "EVAL_MEDICAL_NECESSITY",
      section: "Evaluation",
      title: "Medical Necessity",
      keyComment: "Documentation shows reason services are needed, supported with diagnosis and change in status.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["reasonForTherapy", "medicalDiagnosis", "functionalChange"],
      fullCreditDescription: "A patient-specific line from diagnosis/change in status, through impairment and functional limitation, to the need for a skilled therapist and the expected benefit or risk without treatment — not generic boilerplate.",
    },
    {
      id: "EVAL_ASSESSMENT_SUMMARY",
      section: "Evaluation",
      title: "Assessment Summary",
      keyComment: "Clinical impressions, reason for skilled services, risk factors, recent falls in PCC, change in functional levels.",
      maxPoints: 4,
      scoringType: "holistic-0-4",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      pcc: {
        dependent: true,
        entireCriterion: false,
        reasonTemplate: "The Key expects any recent falls cited in the assessment summary to be documented in PCC, which cannot be confirmed from this record.",
        recommendedAction: "Confirm any falls referenced in the assessment summary against PCC nursing/incident documentation.",
      },
      evidenceTargets: ["reasonForTherapy", "complexities", "functionalChange"],
      fullCreditDescription: "Synthesizes clinical impression, reason for skilled services, risk factors, functional change, and (when applicable) falls into a patient-specific narrative rather than restating dropdown fields.",
    },

    // ==================================================================
    // SECTION: Plan of Care/Treatment (6 pts)
    // ==================================================================
    {
      id: "EVAL_LTG_JUSTIFICATION",
      section: "Plan of Care/Treatment",
      title: "LTG Justification",
      keyComment: "Long-term goals are greater than CLOF and supported by CPT/diagnosis codes and reason for referral.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["longTermGoals", "plannedCptCodes", "medicalDiagnosis", "reasonForReferral"],
      fullCreditDescription: "Every long-term goal targets an outcome above the documented CLOF, supported by the CPT codes / diagnosis / reason for referral on file.",
    },
    {
      id: "EVAL_STG_APPROPRIATE",
      section: "Plan of Care/Treatment",
      title: "STG Appropriate and within LTG",
      keyComment: "Short-term goals are appropriate and function inside corresponding long-term goals.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["shortTermGoals", "longTermGoals", "goalMapping"],
      fullCreditDescription: "Every short-term goal is a functional, measurable, logical intermediate step that maps to a long-term goal.",
    },

    // ==================================================================
    // SECTION: Progress Notes (12 pts)
    // ==================================================================
    {
      id: "PN_COMPLETED_TIMELY",
      section: "Progress Notes",
      title: "Completed Timely",
      keyComment: "Same day = 3, within 24 hrs = 2, same week = 1, anything greater = 0.",
      maxPoints: 3,
      scoringType: "timeliness-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      timingRules: [
        { calendarDays: 0, points: 3 },
        { calendarDays: 1, points: 2 },
        { calendarDaysMin: 2, calendarDays: 6, points: 1 }, // "same week" — treated as up to 6 calendar days
        { calendarDaysMin: 7, points: 0 },
      ],
      dateSource: "progress_report_original_signature",
      prohibitedDateSources: ["cosignature", "physician_signature", "revision_signature"],
      evidenceTargets: ["progressReportPeriodEnd", "originalSignatureDate"],
      fullCreditDescription: "Progress report's ORIGINAL signature date is the same calendar day as the reporting period's end DOS. A cosignature or later revision signature never changes this score.",
    },
    {
      id: "PN_PATIENT_RESPONSE",
      section: "Progress Notes",
      title: "Patient's Response to Treatment",
      keyComment: "Comments required for goals without progress; barriers summarized.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["progressReportPatientProgress", "goalLifecycle"],
      fullCreditDescription: "Patient-specific narrative response documented; any goal without progress carries an explanatory comment; barriers are summarized rather than omitted.",
    },
    {
      id: "PN_POC_MODIFICATIONS",
      section: "Progress Notes",
      title: "Modifications in the POC",
      keyComment: "Plan/goal changes are tracked with baseline vs. current.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["goalLifecycle"],
      fullCreditDescription: "Where a goal's status, target, or approach changed, the progress report documents baseline vs. current and the reason; goals continuing unchanged need no modification note.",
    },
    {
      id: "PN_TREATMENT_FREQUENCY",
      section: "Progress Notes",
      title: "Treatment Frequency",
      keyComment: "Treatment provided at the frequency set by the original eval, recert, or addendum; refusals entered.",
      maxPoints: 3,
      scoringType: "frequency-deviation-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      toleranceBand: { type: "zero_tolerance", varianceVisitsAllowed: 0, appliesToOverAndUnderFrequency: true },
      ambiguityNote: "Only observed data point is an over-frequency case (7–8 visits vs. 5 ordered, scored 0 by the human). Zero-tolerance shipped as the default and made a config value, not a hard-coded rule.",
      evidenceTargets: ["frequencyAnalysis"],
      fullCreditDescription: "Actual unique treatment DOS in the reporting period matches the ordered frequency (accounting for documented refusals); any deviation, over or under, scores 0 under the current confirmed tolerance.",
    },

    // ==================================================================
    // SECTION: Daily Notes / Treatment Encounter Notes (18 pts)
    // ==================================================================
    {
      id: "DN_PATIENT_RESPONSE",
      section: "Daily Notes",
      title: "Patient Response to Treatment",
      keyComment: "Dropdowns must be supported by patient-specific responses, not repetitive.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["dailyNoteEncounters", "documentationSimilarity"],
      fullCreditDescription: "Response-to-treatment narrative is patient-specific across the episode's daily notes, not a repeated stock phrase. Never labeled 'repetitive' from common therapy terminology alone — flagged as 'Potential repetitive/template documentation — reviewer validation recommended' when uncertain.",
    },
    {
      id: "DN_TREATMENT_PROGRESSION",
      section: "Daily Notes",
      title: "Treatment Strategies Reflect Progression/Skill",
      keyComment: "Must include measurable/objective info and specific clinician strategies.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["dailyNoteEncounters"],
      fullCreditDescription: "Narrative distinguishes skilled clinician intervention (facilitation, cueing progression, grading of task difficulty, hands-on technique) from mere patient activity description; measurable/objective detail is present.",
    },
    {
      id: "DN_ATTENDANCE_COMPLIANCE",
      section: "Daily Notes",
      title: "Reflects Attendance/Compliance",
      keyComment: "Missed visit entry and communication/rescheduling attempt required.",
      maxPoints: 3,
      scoringType: "frequency-deviation-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      toleranceBand: { type: "zero_tolerance", varianceVisitsAllowed: 0, appliesToOverAndUnderFrequency: true },
      ambiguityNote: "Shares the Treatment Frequency Engine's zero-tolerance default (confirmed) with PN_TREATMENT_FREQUENCY — see that criterion's note.",
      evidenceTargets: ["frequencyAnalysis"],
      fullCreditDescription: "Daily notes exist for every ordered visit date (or a documented missed-visit/reschedule/refusal entry exists for any gap); frequency matches the ordered plan under the confirmed zero-tolerance rule.",
    },
    {
      id: "DN_CAREGIVER_EDUCATION",
      section: "Daily Notes",
      title: "Caregiver Education",
      keyComment: "Without repetition, addressing barriers/discharge readiness.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["dailyNoteEncounters"],
      fullCreditDescription: "Patient/caregiver education is documented with content beyond generic 'verbal instruction', addresses barriers or discharge readiness, and is not repeated verbatim across encounters.",
    },
    {
      id: "DN_LINKED_TO_GOALS",
      section: "Daily Notes",
      title: "Linked to Specific Goals",
      keyComment: "Tied to POC with correct CPT.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["dailyNoteEncounters", "goalLifecycle"],
      fullCreditDescription: "Each billed CPT code maps (via its typical intervention target — e.g. 97116 gait training → gait/mobility goal, 97535 self-care training → ADL goal, 97112 neuromuscular reeducation → balance/coordination/motor-control goal) to an active STG/LTG. A CPT code alone does not prove the linkage; the narrative must support it.",
    },
    {
      id: "DN_DISCONTINUE_WHEN_MET",
      section: "Daily Notes",
      title: "Discontinued When Goal Met",
      keyComment: "CPT codes billed are working toward an unmet goal within the POC.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: true,
      evidenceTargets: ["goalLifecycle", "dailyNoteEncounters"],
      fullCreditDescription: "No goal continues to receive targeted billing after its documented met-date without an explicit modification/new-goal note. N/A when no goal has yet been met in the episode.",
    },

    // ==================================================================
    // SECTION: Recertification (24 pts) — N/A when discharged before a
    // recert falls due; not exercised by the James Askew fixture episode.
    // ==================================================================
    {
      id: "RC_LTG_JUSTIFIED",
      section: "Recertification",
      title: "LTGs Are Justified",
      keyComment: "—",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: true,
      evidenceTargets: ["recertLongTermGoals"],
      fullCreditDescription: "Long-term goals carried/updated at recertification remain justified against current CLOF/diagnosis. N/A if the episode discharged before a recertification fell due.",
    },
    {
      id: "RC_STG_APPROPRIATE",
      section: "Recertification",
      title: "STGs Are Appropriate",
      keyComment: "—",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: true,
      evidenceTargets: ["recertShortTermGoals"],
      fullCreditDescription: "Short-term goals at recertification remain appropriate and map to a long-term goal. N/A if no recertification occurred.",
    },
    {
      id: "RC_TREATMENT_RELEVANT_TO_IMPAIRMENT",
      section: "Recertification",
      title: "Treatment or Modifications Relevant to Impairment",
      keyComment: "—",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: true,
      evidenceTargets: ["recertNarrative"],
      fullCreditDescription: "Any treatment/POC modification at recertification is relevant to the documented impairment. N/A if no recertification occurred.",
    },
    {
      id: "RC_TREATMENT_RELATED_TO_GOALS",
      section: "Recertification",
      title: "Treatment Related to Goals",
      keyComment: "—",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: true,
      evidenceTargets: ["recertNarrative", "recertShortTermGoals"],
      fullCreditDescription: "Continued treatment at recertification is related to the active goals. N/A if no recertification occurred.",
    },
    {
      id: "RC_AMOUNT_FREQUENCY_DURATION",
      section: "Recertification",
      title: "Amount/Frequency/Duration",
      keyComment: "Frequency changes require justification in the continued-skill section.",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: true,
      evidenceTargets: ["recertFrequency"],
      fullCreditDescription: "Any change to amount/frequency/duration at recertification is explicitly justified in the continued-services narrative. N/A if no recertification occurred.",
    },
    {
      id: "RC_CONTINUED_SERVICES_JUSTIFIED",
      section: "Recertification",
      title: "Justification for Continued Services",
      keyComment: "—",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: true,
      evidenceTargets: ["recertNarrative"],
      fullCreditDescription: "A patient-specific rationale for continuing skilled services is documented. N/A if no recertification occurred.",
    },
    {
      id: "RC_ORDERS_IN_PCC",
      section: "Recertification",
      title: "Orders in PCC",
      keyComment: "Yes = 3, no = 0.",
      maxPoints: 3,
      scoringType: "binary-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: true,
      pcc: {
        dependent: true,
        entireCriterion: true,
        reasonTemplate: "The uploaded therapy documentation does not contain PCC order evidence for the recertification.",
        recommendedAction: "Verify the recertification order directly in PCC.",
        acceptableProxyEvidence: false,
      },
      evidenceTargets: ["recertFrequency"],
      fullCreditDescription: "A matching recertification order is confirmed present in PCC. N/A if no recertification occurred.",
    },
    {
      id: "RC_COMPLETED_TIMELY",
      section: "Recertification",
      title: "Completed Timely",
      keyComment: "Same day = 3, within 24 hrs = 2, within 48 hrs = 1, all greater = 0.",
      maxPoints: 3,
      scoringType: "timeliness-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: true,
      timingRules: [
        { calendarDays: 0, points: 3 },
        { calendarDays: 1, points: 2 },
        { calendarDays: 2, points: 1 },
        { calendarDaysMin: 3, points: 0 },
      ],
      dateSource: "recert_original_signature",
      evidenceTargets: ["recertSignatureDate"],
      fullCreditDescription: "Recertification's original signature date vs. its due/DOS date. N/A if no recertification occurred.",
    },

    // ==================================================================
    // SECTION: Discharge Summary (12 pts)
    // ==================================================================
    {
      id: "DC_ALL_GOALS_ADDRESSED",
      section: "Discharge Summary",
      title: "All Goals Addressed",
      keyComment: "—",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["goalLifecycle"],
      fullCreditDescription: "Every STG/LTG from the Plan of Care appears in the discharge goal table with a terminal status (Met / Partially Met / Not Met / Discontinued). A goal disappearing without any discharge-table entry is flagged, not silently dropped.",
    },
    {
      id: "DC_REASON_FOR_DISCHARGE",
      section: "Discharge Summary",
      title: "Reason for Discharge",
      keyComment: "—",
      maxPoints: 3,
      scoringType: "holistic-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      evidenceTargets: ["dischargeReason"],
      fullCreditDescription: "A specific, patient-relevant reason for discharge is documented (goal achievement, physician/case-manager order, highest practical level achieved, etc.), not a bare boilerplate label with no supporting context.",
    },
    {
      id: "DC_COMPLETED_TIMELY",
      section: "Discharge Summary",
      title: "Completed Timely",
      keyComment: '"Document completed timely" — no thresholds defined anywhere in the Key.',
      maxPoints: 3,
      scoringType: "timeliness-pending",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "NEEDS_CONFIRMATION",
      allowNA: false,
      timingRules: null, // DO NOT invent thresholds — see PRE_BUILD_RUBRIC_ANALYSIS.md Decision #1
      dateSource: "discharge_original_signature",
      ambiguityNote:
        "Key defines no thresholds. Two same-episode data points disagree in shape (PT: 5/25→5/27, 2-day gap, human-scored 2/3; OT: 5/25→5/28, 3-day gap, never scored). Report elapsed calendar-day difference as fact; status PENDING_RUBRIC_CONFIRMATION; excluded from the scored denominator; potential points tracked separately until MCOA supplies actual thresholds.",
      evidenceTargets: ["dischargeDOS", "dischargeSignatureDate"],
      fullCreditDescription: "PENDING organizational confirmation of the actual timeliness thresholds for this criterion.",
    },
    {
      id: "DC_ORDERS_IN_PCC",
      section: "Discharge Summary",
      title: "Orders in PCC",
      keyComment: "Yes = 3, no = 0.",
      maxPoints: 3,
      scoringType: "binary-0-3",
      applicableDisciplines: ["PT", "OT", "SLP"],
      ruleStatus: "CONFIRMED",
      allowNA: false,
      pcc: {
        dependent: true,
        entireCriterion: true,
        reasonTemplate: "The uploaded therapy documentation does not contain PCC order evidence for the discharge. Discharge-disposition/home-health-referral language (e.g. 'Home with HH') is not, by itself, treated as proof of a matching PCC order.",
        recommendedAction: "Verify the discharge order directly in PCC.",
        acceptableProxyEvidence: false,
      },
      ambiguityNote: "Evaluator Audit 2 scored this 3/3 off discharge-disposition language alone ('Home with HH') — that is a Human Judgment Difference to report in the Development Validation Report (confirmed decision, not replicated) per PRE_BUILD_RUBRIC_ANALYSIS.md Decision #2. Same PCC-evidence standard as the Evaluation-section Orders in PCC criterion — no Discharge-only exception.",
      evidenceTargets: ["dischargeRecommendations"],
      fullCreditDescription: "A matching discharge order (or home-health referral order, if that is what PCC records) is confirmed present in PCC.",
    },
  ],
};

export const EVALUATOR_AUDIT_MAX_POINTS = evaluatorAuditRubric.criteria.reduce((sum, c) => sum + c.maxPoints, 0);
